version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api.dockerfile
    container_name: api
    command: './build/index.js'
    ports:
      - 3000:3000
    depends_on:
      - mongo
  
  api-watch:
    build:
      context: .
      dockerfile: dockerfiles/api-watch.dockerfile
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./src:/src
      - ./config:/config

  mongo:
    image: mongo:4.2
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:6.0.9
    container_name: redis
