version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api.dockerfile
    container_name: integration-test-api
    command: './build/index.js'
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.2
    container_name: integration-test-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./test-integration/mongo-init:/docker-entrypoint-initdb.d      

  redis:
    image: redis:6.0.9
    container_name: integration-test-redis

  integration-tests:
    build:
      context: ./test-integration
      dockerfile: ../dockerfiles/test-integration.dockerfile
    container_name: integration-tests
    depends_on:
      - api
