name: 'Integration-tests'
on:
  push:

jobs:
  Integration-Tests:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Start mongo DB
        run: docker-compose -f ./test-integration.docker-compose.yml up -d mongo
      - name: Start API
        run: docker-compose -f ./test-integration.docker-compose.yml up -d api
      - name: Run tests
        run: docker-compose -f ./test-integration.docker-compose.yml up --abort-on-container-exit integration-tests
